### ISSUE TITLE
Скласти маршрут

### ISSUE THREAD

**Issue by cocosynka** [cocosynka/First#3]
Вершини на які будемо підніматися
- [x] Ребра
- [x] Бребенескул
- [x] Шпиці
- [x] Піп Іван

**Comment by cocosynka** [comment]
Пропоную ще додати Гутин Томнатик

**Comment by ShyshkaUliana** [comment]
Будемо наймати екскурсовода?

**Comment by ShyshkaUliana** [comment]
Про Гутин Томнатик не чула, але думаю буде цікаво відвідати це місце

**Comment by cocosynka** [comment]
Переночуємо біля Несамовитого!

**Comment by ShyshkaUliana** [comment]
Будемо спати в наметах?

**Comment by cocosynka** [comment]
> Будемо спати в наметах?

Звичайно:)
